In [91]:
#ADAM HENZE
#COMPSCI 4200
#Hw 5

import numpy as np
import random
import pandas as pd
from collections import Counter

Bday = 24
d = 1 + (Bday % 2)
m = 2 + (Bday // 2)
k = m // d

print(Bday, d, m, k)

24 1 14 14


#Question 1
Normally when using arithmatic operations on arrays, the arrays need to be of the same size and shape. Broadcasting allows a scalar value to be applied to all members of an array as if it were the same size and shape.

In [92]:
#NOTE!!!: My D value is 1, 
#but I wanted a more than 1d array
#so the array is intentionally reshaped
#to make question more interesting

numarr = np.arange(1,k+1).reshape(2,7)
print(numarr)

cubearr = numarr * numarr
print(cubearr)
marr = numarr + m
print(marr)
mxarr = numarr * m
print(mxarr)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[[  1   4   9  16  25  36  49]
 [ 64  81 100 121 144 169 196]]
[[15 16 17 18 19 20 21]
 [22 23 24 25 26 27 28]]
[[ 14  28  42  56  70  84  98]
 [112 126 140 154 168 182 196]]


In [93]:
#Question 2
randarr = np.random.randint(100, size=(2,4))
print(randarr.flatten('F'))
print(randarr.ravel())
print(randarr)

[43 37 97 56 96 70 43 26]
[43 97 96 43 37 56 70 26]
[[43 97 96 43]
 [37 56 70 26]]


In [94]:
#Question 3
    #Apologies

In [95]:
#Question 4
    #Apologies

In [96]:
#Question 5
array1 = np.array([1,3,3,4,5,6,7,8,9])
array2 = np.array([[1,2,3],[4,6,6]])
array3 = np.arange(1,11).reshape(5,2)

#function for finding median
def npmedian(array):
    newarr = array.flatten('F')
    size = len(newarr)
    #check for even or odd length, return middle
    if ((len(newarr) % 2) == 0):
        val = ((newarr[(len(newarr)//2) - 1] + newarr[(len(newarr)//2)]) / 2)
        return val
    else:
        val = newarr[(len(newarr)//2)]
        return val

#mode func
def npmode(array):
    newarr = array.flatten('F')
    size = len(newarr)
    if len(newarr) == 1:
        return newarr[0]

    #count members
    counts = dict(Counter(newarr))

    
    #if count goes above 1 or indx set new mode, return
    indx = 1
    for val in counts:
        if counts[val] > indx:
            indx = counts[val]
            mode = val
            return mode
    
print(npmedian(array1))
print(npmedian(array2))
print(npmedian(array3))

print(npmode(array1))
print(npmode(array2))
print(npmode(array3))

5
4.0
5.5
3
6
None


In [97]:
#Question 6
#b
random_array = np.random.randint(0, 100, (5, 5))
bincounts = np.bincount(random_array.flatten())
#parse bincounts and only print values > 1
for x in range(len(bincounts)):
    if bincounts[x] > 0:
        print(x,' counts = ',bincounts[x])

#c
list1 = np.array([[0, d], [2 * d, 3 * d]])
list2 = np.array([[m, 5], [6 * m, 4 * m]])
result = np.concatenate((list1, list2), axis=0)
print(result)

0  counts =  1
3  counts =  1
13  counts =  1
15  counts =  1
19  counts =  1
20  counts =  1
22  counts =  1
23  counts =  1
26  counts =  1
32  counts =  1
37  counts =  1
38  counts =  1
39  counts =  1
44  counts =  1
50  counts =  1
58  counts =  1
59  counts =  1
67  counts =  1
75  counts =  1
77  counts =  1
83  counts =  1
85  counts =  1
86  counts =  1
94  counts =  1
97  counts =  1
[[ 0  1]
 [ 2  3]
 [14  5]
 [84 56]]


In [98]:
#Question 7
series_a = pd.Series([k, m, d + m, m - k])
series_b = pd.Series([100 * k] * 5)
#randoms for series c
random_numbers = [random.uniform(0, 100) for _ in range(d * m)]
series_c = pd.Series(random_numbers)
#set stats
statistics_c = series_c.describe()
#set index
temperature = pd.Series([98.6, 98.9, 100.2, 97.9], index=['Julie', 'Eva', 'Adrian', 'Amber'])
data_dict = {'Julie': 98.6, 'Eva': 98.9, 'Adrian': 100.2, 'Amber': 97.9}
#series from dict
series_e = pd.Series(data_dict)

print("Series (a):")
print(series_a)
print("\nSeries (b):")
print(series_b)
print("\nSeries (c):")
print(statistics_c)
print("\nSeries (d):")
print(temperature)
print("\nSeries (e):")
print(series_e)

Series (a):
0    14
1    14
2    15
3     0
dtype: int64

Series (b):
0    1400
1    1400
2    1400
3    1400
4    1400
dtype: int64

Series (c):
count    14.000000
mean     57.681376
std      30.403896
min       7.260915
25%      33.238265
50%      66.503624
75%      78.654272
max      95.368297
dtype: float64

Series (d):
Julie      98.6
Eva        98.9
Adrian    100.2
Amber      97.9
dtype: float64

Series (e):
Julie      98.6
Eva        98.9
Adrian    100.2
Amber      97.9
dtype: float64


In [99]:
#Question 8
#data
temperature_data = {
    'Maxine': [70.2, 72.5, 68.9],
    'James': [68.4, 71.2, 67.7],
    'Amanda': [75.1, 76.3, 74.8]
}
#make frame
temperatures = pd.DataFrame(temperature_data)
print("DataFrame (a):")
print(temperatures)

#set indices to times.
temperatures.index = ['Morning', 'Afternoon', 'Evening']
print("\nDataFrame (b):")
print(temperatures)

# c
maxine_temperatures = temperatures['Maxine']
print("\nColumn 'Maxine' Temperatures:")
print(maxine_temperatures)

#use loc to find data
# d
morning_temperatures = temperatures.loc['Morning']
print("\nRow 'Morning' Temperatures:")
print(morning_temperatures)

# e
morning_evening_temperatures = temperatures.loc[['Morning', 'Evening']]
print("\nRows 'Morning' and 'Evening' Temperatures:")
print(morning_evening_temperatures)

# f
amanda_maxine_temperatures = temperatures[['Amanda', 'Maxine']]
print("\nColumns 'Amanda' and 'Maxine' Temperatures:")
print(amanda_maxine_temperatures)

#use column and indice selection
# g
amanda_maxine_morning_afternoon = temperatures.loc[['Morning', 'Afternoon'], ['Amanda', 'Maxine']]
print("\nElements for 'Amanda' and 'Maxine' in 'Morning' and 'Afternoon':")
print(amanda_maxine_morning_afternoon)

#stats via describe
# h
temperature_statistics = temperatures.describe()
print("\nDescriptive Statistics:")
print(temperature_statistics)

# i
temperatures_transposed = temperatures.T
print("\nTransposed DataFrame:")
print(temperatures_transposed)

#sort based on axis
# j
temperatures_sorted = temperatures.sort_index(axis=1)
print("\nDataFrame with Sorted Column Names:")
print(temperatures_sorted)

DataFrame (a):
   Maxine  James  Amanda
0    70.2   68.4    75.1
1    72.5   71.2    76.3
2    68.9   67.7    74.8

DataFrame (b):
           Maxine  James  Amanda
Morning      70.2   68.4    75.1
Afternoon    72.5   71.2    76.3
Evening      68.9   67.7    74.8

Column 'Maxine' Temperatures:
Morning      70.2
Afternoon    72.5
Evening      68.9
Name: Maxine, dtype: float64

Row 'Morning' Temperatures:
Maxine    70.2
James     68.4
Amanda    75.1
Name: Morning, dtype: float64

Rows 'Morning' and 'Evening' Temperatures:
         Maxine  James  Amanda
Morning    70.2   68.4    75.1
Evening    68.9   67.7    74.8

Columns 'Amanda' and 'Maxine' Temperatures:
           Amanda  Maxine
Morning      75.1    70.2
Afternoon    76.3    72.5
Evening      74.8    68.9

Elements for 'Amanda' and 'Maxine' in 'Morning' and 'Afternoon':
           Amanda  Maxine
Morning      75.1    70.2
Afternoon    76.3    72.5

Descriptive Statistics:
          Maxine      James     Amanda
count   3.000000   3.0000

In [100]:
#Question 9
    #Apologies